# Generated by Django 3.1 on 2025-04-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodDatabase',
        ),
        migrations.AddField(
            model_name='food',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='proteins',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
